<a href="https://colab.research.google.com/github/robinkm0610/ML_with_Python-R/blob/main/Basics/Classification_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns


In [2]:
%load_ext rpy2.ipython

In [3]:
df = pd.read_csv(r'Classification preprocessed data Python.csv',header= 0)
df.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  Sold  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347     0    4.0875            1   
1       7.332     12.17280        42  0.046146     1    4.9675            0   
2       7.394     46.19856        38  0.045764     0    4.9675            0   
3       9.268     11.26720        45  0.047151     0    6.0650            1   
4       8.824     11.28960        55  0.039474     0    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

In [4]:
%%R
df <- read.csv(file = "Classification preprocessed data R.csv", header = TRUE)

In [5]:
str(df)

'     price  resid_area  air_qual  room_num   age  teachers  poor_prop  \\\n0     24.0       32.31     0.538     6.575  65.2      24.7       4.98   \n1     21.6       37.07     0.469     6.421  78.9      22.2       9.14   \n2     34.7       37.07     0.469     7.185  61.1      22.2       4.03   \n3     33.4       32.18     0.458     6.998  45.8      21.3       2.94   \n4     36.2       32.18     0.458     7.147  54.2      21.3       5.33   \n..     ...         ...       ...       ...   ...       ...        ...   \n501   22.4       41.93     0.573     6.593  69.1      19.0       9.67   \n502   20.6       41.93     0.573     6.120  76.7      19.0       9.08   \n503   23.9       41.93     0.573     6.976  91.0      19.0       5.64   \n504   22.0       41.93     0.573     6.794  89.3      19.0       6.48   \n505   19.0       41.93     0.573     6.030  80.8      19.0       7.88   \n\n     n_hos_beds  n_hot_rooms  rainfall     parks  Sold  avg_dist  airport_YES  \\\n0         5.480     11.19

In [6]:
df.describe()

price  resid_area    air_qual    room_num         age    teachers  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    22.528854   41.136779    0.554695    6.284634   68.574901   21.544466   
std      9.182176    6.860353    0.115878    0.702617   28.148861    2.164946   
min      5.000000   30.460000    0.385000    3.561000    2.900000   18.000000   
25%     17.025000   35.190000    0.449000    5.885500   45.025000   19.800000   
50%     21.200000   39.690000    0.538000    6.208500   77.500000   20.950000   
75%     25.000000   48.100000    0.624000    6.623500   94.075000   22.600000   
max     50.000000   57.740000    0.871000    8.780000  100.000000   27.400000   

        poor_prop  n_hos_beds  n_hot_rooms    rainfall       parks  \
count  506.000000  506.000000   506.000000  506.000000  506.000000   
mean    12.653063    7.899767    12.864050   39.187747    0.054454   
std      7.141062    1.464939     2.688778   12.497221    0.010632   
min      1.730000    5.268000    10.057600    6.000000    0.033292   
25%      6.950000    6.659000    11.189800   28.000000    0.046464   
50%     11.360000    7.963000    12.720000   39.000000    0.053507   
75%     16.955000    9.076000    14.170800   50.000000    0.061397   
max     37.970000   10.876000    46.198560   60.000000    0.086711   

             Sold    avg_dist  airport_YES  waterbody_Lake  \
count  506.000000  506.000000   506.000000      506.000000   
mean     0.454545    3.795104     0.551383        0.191700   
std      0.498422    2.105859     0.497845        0.394028   
min      0.000000    1.127500     0.000000        0.000000   
25%      0.000000    2.100625     0.000000        0.000000   
50%      0.000000    3.207500     1.000000        0.000000   
75%      1.000000    5.187500     1.000000        0.000000   
max      1.000000   12.127500     1.000000        1.000000   

       waterbody_Lake and River  waterbody_River  
count                506.000000       506.000000  
mean                   0.140316         0.361660  
std                    0.347659         0.480957  
min                    0.000000         0.000000  
25%                    0.000000         0.000000  
50%                    0.000000         0.000000  
75%                    0.000000         1.000000  
max                    1.000000         1.000000

In [7]:
X = df[['price']]
y = df['Sold']

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
clf_lrs = LogisticRegression()
clf_lrs.fit(X,y)


LogisticRegression()

In [10]:
clf_lrs.coef_

array([[-0.03571865]])

In [11]:
clf_lrs.intercept_

array([0.61477516])

In [12]:
import statsmodels.api as sn

In [13]:
X_cons = sn.add_constant(X)

In [14]:
X_cons.head()

const  price
0    1.0   24.0
1    1.0   21.6
2    1.0   34.7
3    1.0   33.4
4    1.0   36.2

In [15]:
import statsmodels.discrete.discrete_model as sm

In [16]:
logit = sm.Logit(y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


In [17]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Mon, 24 Jun 2024   Pseudo R-squ.:                 0.01788
Time:                        15:00:22   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

In [18]:
%%R
glm.fit = glm(Sold ~ price, data = df, family = binomial)
summary(glm.fit)


Call:
glm(formula = Sold ~ price, family = binomial, data = df)

Coefficients:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  0.61486    0.24751   2.484 0.012986 *  
price       -0.03572    0.01045  -3.417 0.000632 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 697.28  on 505  degrees of freedom
Residual deviance: 684.81  on 504  degrees of freedom
AIC: 688.81

Number of Fisher Scoring iterations: 4



In [19]:
X = df.loc[:,df.columns != 'Sold']
y = df['Sold']

In [20]:
clr_lr = LogisticRegression()
clr_lr.fit(X,y)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [21]:
clr_lr.coef_

array([[-0.24635272, -0.01729728, -0.11019194,  0.86257488, -0.00599849,
         0.22820422, -0.21021246,  0.18007206, -0.09087452, -0.00704891,
        -0.00499194, -0.3261136 , -0.10521032, -0.09486934, -0.01512301,
         0.2017964 ]])

In [22]:
clr_lr.intercept_

array([0.0167118])

In [23]:
X_cons = sn.add_constant(X)

In [24]:
logit = sm.Logit(y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.556433
         Iterations 6


In [25]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      489
Method:                           MLE   Df Model:                           16
Date:                Mon, 24 Jun 2024   Pseudo R-squ.:                  0.1924
Time:                        15:00:23   Log-Likelihood:                -281.56
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 9.930e-21
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -2.1383      2.649     -0.807      0.420      -7.331       3.054
price                       -0.2741      0.033     -8.313      0.000      -0.339      -0.209
resid_area                   0.0192      0.027      0.720      0.471      -0.033       0.071
air_qual                    -7.4183      2.691     -2.757      0.006     -12.693      -2.144
room_num                     1.1067      0.277      4.001      0.000       0.565       1.649
age                         -0.0020      0.007     -0.302      0.762      -0.015       0.011
teachers                     0.3150      0.064      4.937      0.000       0.190       0.440
poor_prop                   -0.2077      0.034     -6.149      0.000      -0.274      -0.141
n_hos_beds                   0.1760      0.071      2.467      0.014       0.036       0.316
n_hot_rooms                 -0.0742      0.052     -1.439      0.150      -0.175       0.027
rainfall                    -0.0033      0.008     -0.394      0.693      -0.020       0.013
parks                       29.1089     24.177      1.204      0.229     -18.277      76.495
avg_dist                    -0.4017      0.098     -4.118      0.000      -0.593      -0.211
airport_YES                 -0.1524      0.211     -0.723      0.469      -0.565       0.261
waterbody_Lake              -0.1032      0.304     -0.340      0.734      -0.698       0.492
waterbody_Lake and River    -0.0626      0.328     -0.191      0.849      -0.705       0.580
waterbody_River              0.2394      0.256      0.937      0.349      -0.262       0.740
============================================================================================
"""

In [26]:
%%R
glm.fit = glm(Sold ~., data = df, family = binomial)
summary(glm.fit)


Call:
glm(formula = Sold ~ ., family = binomial, data = df)

Coefficients:
                         Estimate Std. Error z value Pr(>|z|)    
(Intercept)             -2.138280   2.649317  -0.807  0.41961    
price                   -0.274084   0.032972  -8.313  < 2e-16 ***
resid_area               0.019211   0.026674   0.720  0.47140    
air_qual                -7.418344   2.691109  -2.757  0.00584 ** 
room_num                 1.106728   0.276645   4.001 6.32e-05 ***
age                     -0.001993   0.006595  -0.302  0.76247    
teachers                 0.315004   0.063810   4.937 7.95e-07 ***
poor_prop               -0.207690   0.033776  -6.149 7.80e-10 ***
airportYES              -0.152400   0.210677  -0.723  0.46944    
n_hos_beds               0.175963   0.071336   2.467  0.01364 *  
n_hot_rooms             -0.074215   0.051574  -1.439  0.15015    
waterbodyLake           -0.103179   0.303632  -0.340  0.73400    
waterbodyLake.and.River -0.062613   0.327945  -0.191  0.84858    


# Predicting and confusion matrix

In [27]:
clr_lr.predict_proba(X)

array([[0.12706582, 0.87293418],
       [0.39755229, 0.60244771],
       [0.98072387, 0.01927613],
       ...,
       [0.28595357, 0.71404643],
       [0.28062865, 0.71937135],
       [0.16347383, 0.83652617]])

In [28]:
y_pred = clr_lr.predict(X)
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [29]:
y_pred_03 = (clr_lr.predict_proba(X)[:,1] >= 0.3)
y_pred_03

array([ True,  True, False,  True, False, False,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False, False,

In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y,y_pred)

array([[196,  80],
       [ 81, 149]])

In [31]:
confusion_matrix(y,y_pred_03)

array([[121, 155],
       [ 18, 212]])

In [32]:
from sklearn.metrics import precision_score, recall_score, accuracy_score, roc_auc_score


In [33]:
precision_score(y, y_pred)

0.6506550218340611

In [34]:
recall_score(y, y_pred)

0.6478260869565218

In [35]:
roc_auc_score(y, y_pred)

0.6789855072463769

In [36]:
%%R
glm.probs = predict(glm.fit, type = "response")

In [37]:
%%R
glm.probs[1:10]

         1          2          3          4          5          6          7 
0.85141600 0.67065484 0.03402370 0.27038629 0.09185864 0.20166690 0.43390218 
         8          9         10 
0.14510166 0.03966122 0.41134502 


In [38]:
%%R
glm.pred = rep("NO", 506)
glm.pred[glm.probs > 0.5] = "YES"

In [39]:
%%R
table(glm.pred, df$Sold)

        
glm.pred   0   1
     NO  197  81
     YES  79 149


#LDA

In [40]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [41]:
clf_lda = LinearDiscriminantAnalysis()
clf_lda.fit(X,y)

LinearDiscriminantAnalysis()

In [42]:
y_pred_lda = clf_lda.predict(X)
y_pred_lda

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [43]:
confusion_matrix(y,y_pred_lda)

array([[192,  84],
       [ 79, 151]])

In [44]:

%%R
require('MASS')

In [46]:
%%R
lda.fit = lda(Sold ~., data = df)

In [48]:
%%R
lda.pred = predict(lda.fit,df)

In [49]:
%%R
lda.pred$posterior

             0           1
1   0.20393265 0.796067351
2   0.37998440 0.620015597
3   0.94246036 0.057539640
4   0.71573650 0.284263501
5   0.88775865 0.112241349
6   0.76539066 0.234609337
7   0.55317603 0.446823971
8   0.83681609 0.163183915
9   0.94136826 0.058631737
10  0.58641639 0.413583612
11  0.52821183 0.471788171
12  0.36262795 0.637372049
13  0.71381570 0.286184304
14  0.68410067 0.315899331
15  0.46935599 0.530644007
16  0.44442366 0.555576340
17  0.64226676 0.357733242
18  0.74211194 0.257888055
19  0.70265865 0.297341346
20  0.46172143 0.538278574
21  0.82390451 0.176095495
22  0.66399532 0.336004682
23  0.70044143 0.299558569
24  0.79121426 0.208785742
25  0.71242752 0.287572482
26  0.54819250 0.451807499
27  0.67824471 0.321755294
28  0.68253225 0.317467753
29  0.62293086 0.377069136
30  0.50813889 0.491861106
31  0.66954101 0.330458994
32  0.34301774 0.656982261
33  0.81924424 0.180755763
34  0.57833186 0.421668138
35  0.56925724 0.430742761
36  0.17833076 0.821669245
3

In [50]:
%%R
lda.class = lda.pred$class
table(lda.class, df$Sold)

         
lda.class   0   1
        0 192  79
        1  84 151


In [53]:
%%R
sum(lda.pred$posterior[,1] > 0.8)

[1] 76


In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [56]:
print(X_train.shape)
print(X_test.shape)

(404, 16)
(102, 16)


In [58]:
print(y_train.shape)
print(y_test.shape)

(404,)
(102,)


In [59]:
clf_LR = LogisticRegression()
clf_LR.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [60]:
y_test_pred = clf_LR.predict(X_test)

In [61]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [62]:
confusion_matrix(y_test, y_test_pred)

array([[37, 21],
       [14, 30]])

In [63]:
accuracy_score(y_test, y_test_pred)

0.6568627450980392

In [66]:
%%R
install.packages("caTools")

(as ‘lib’ is unspecified)














	‘/tmp/RtmpAm2lI0/downloaded_packages’



In [68]:
%%R
require('caTools')

In [69]:
%%R
set.seed(0)
split = sample.split(df, SplitRatio = 0.8)
train_set = subset(df, split == TRUE)
test_set = subset(df, split == FALSE)

In [75]:
%%R
train_set = glm(Sold ~., data = train_set, family = binomial)

  cannot coerce class ‘c("glm", "lm")’ to a data.frame




Error in as.data.frame.default(data) : 
  cannot coerce class ‘c("glm", "lm")’ to a data.frame


In [76]:
%%R
test.probs = predict(train.fit, test_set, type = "response")

  object 'train.fit' not found




Error in (function (expr, envir = parent.frame(), enclos = if (is.list(envir) ||  : 
  object 'train.fit' not found


In [72]:
%%R
test.pred = rep("NO", 120)
test.pred[test.probe > 0.5] = "YES"

  object 'test.probe' not found




Error in (function (expr, envir = parent.frame(), enclos = if (is.list(envir) ||  : 
  object 'test.probe' not found


In [78]:
%%R
table(test.pred, test_set$Sold)

         
test.pred  0  1
       NO 68 52


K- Nearest Neighbors

In [80]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X_train)
X_train_s = scaler.transform(X_train)


In [81]:
scaler = preprocessing.StandardScaler().fit(X_test)
X_test_s = scaler.transform(X_test)

In [82]:
X_test_s

array([[ 3.46427198e-02, -1.26009787e+00, -7.59976330e-01, ...,
        -4.93864798e-01, -3.98862018e-01, -7.54473836e-01],
       [ 3.08888478e+00,  1.09537107e+00,  6.84309089e-01, ...,
        -4.93864798e-01, -3.98862018e-01, -7.54473836e-01],
       [ 7.92301952e-02,  4.28041039e-01,  1.73890573e-04, ...,
        -4.93864798e-01, -3.98862018e-01, -7.54473836e-01],
       ...,
       [-4.00085165e-01, -9.60512654e-01, -8.19099125e-01, ...,
        -4.93864798e-01, -3.98862018e-01,  1.32542701e+00],
       [ 6.47720506e-01, -9.50442563e-02, -5.15039037e-01, ...,
        -4.93864798e-01, -3.98862018e-01, -7.54473836e-01],
       [-2.77469608e-01, -4.16820968e-01, -2.53209516e-01, ...,
        -4.93864798e-01,  2.50713268e+00, -7.54473836e-01]])

In [83]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn_1 = KNeighborsClassifier(n_neighbors = 1)
clf_knn_1.fit(X_train_s, y_train)

KNeighborsClassifier(n_neighbors=1)

In [84]:
confusion_matrix(y_test, clf_knn_1.predict(X_test_s))

array([[30, 28],
       [19, 25]])

In [85]:
accuracy_score(y_test, clf_knn_1.predict(X_test_s))

0.5392156862745098

In [87]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn_3 = KNeighborsClassifier(n_neighbors = 3)
clf_knn_3.fit(X_train_s, y_train)

KNeighborsClassifier(n_neighbors=3)

In [88]:
accuracy_score(y_test, clf_knn_3.predict(X_test_s))

0.5392156862745098

In [90]:
from sklearn.model_selection import GridSearchCV

In [94]:
params = {'n_neighbors' : np.arange(1,10)}
params

{'n_neighbors': array([1, 2, 3, 4, 5, 6, 7, 8, 9])}

In [95]:
grid_search_cv = GridSearchCV(KNeighborsClassifier(), params)

In [96]:
grid_search_cv.fit(X_train_s, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([1, 2, 3, 4, 5, 6, 7, 8, 9])})

In [97]:
grid_search_cv.best_params_

{'n_neighbors': 9}

In [100]:
optimised_KNN = grid_search_cv.best_estimator_

In [101]:
y_test_pred = optimised_KNN.predict(X_test_s)

In [103]:
confusion_matrix(y_test, y_test_pred)

array([[36, 22],
       [18, 26]])

In [104]:
accuracy_score(y_test, y_test_pred)

0.6078431372549019