<a href="https://colab.research.google.com/github/robinkm0610/ML_with_Python-R/blob/main/Basics/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Movie_regression.csv', header = 0)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [4]:
df['Time_taken'].fillna(value = df['Time_taken'].mean(), inplace = True)

In [5]:
df = pd.get_dummies(df, columns = ['3D_available', 'Genre'],drop_first=True)

In [6]:
X= df.loc[:, df.columns != 'Collection']
y = df['Collection']

In [7]:
X.shape

(506, 19)

In [8]:
y.shape

(506,)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [10]:
X_train.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
220            27.1618               67.40               0.493  38612.805   
71             23.1752               76.62               0.587  33113.355   
240            22.2658               64.86               0.572  38312.835   
6              21.7658               70.74               0.476  33396.660   
417           538.8120               91.20               0.321  29463.720   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
220         162.0               8.485                8.640            8.485   
71           91.0               7.280                7.400            7.290   
240         127.8               6.755                6.935            6.800   
6           140.1               7.065                7.265            7.150   
417         162.6               9.135                9.305            9.095   

     Producer_rating  Critic_rating  Trailer_views  Time_taken  \
220            8.670           8.52         480270      174.68   
71             7.455           8.16         491978      200.68   
240            6.840           8.68         470107      204.80   
6              7.400           8.96         459241      139.16   
417            9.165           6.96         302776      172.16   

     Twitter_hastags  Avg_age_actors  Num_multiplex  3D_available_YES  \
220          224.272              23            536             False   
71           263.472              46            400             False   
240          224.320              24            387              True   
6            243.664              41            522              True   
417          301.664              60            589              True   

     Genre_Comedy  Genre_Drama  Genre_Thriller  
220         False        False            True  
71          False        False           False  
240          True        False           False  
6           False        False            True  
417         False        False           False

Standardizing Data

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
sc = StandardScaler().fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [14]:
X_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

Training Regressio Tree

In [30]:
from sklearn.svm import SVR
svr = SVR(kernel = 'linear', C = 500)

In [31]:
svr.fit(X_train_std, y_train)

SVR(C=500, kernel='linear')

In [32]:
#Predict values using trained model

y_test_pred = svr.predict(X_test_std)
y_train_pred = svr.predict(X_train_std)

In [33]:
y_test_pred

array([54172.88652594, 42360.53493594, 47535.6161038 , 18213.44501931,
       48306.49797341, 39911.30264079, 34154.82438396, 43328.81857968,
       30564.16305183, 47083.06891753, 12883.41530221, 38441.56120077,
       37564.58419372,  8833.24108759, 66743.92804381, 61806.13858547,
       38834.69156187, 65442.06460586, 57070.43984968, 43390.83509428,
       53825.48454162, 39211.12088433, 41594.24518385, 58253.12540463,
       43061.94784582, 13500.91595214, 41078.73255014, 29760.22077231,
       74387.42055942, 44639.66629805, 36802.04559594, 37452.7520558 ,
       37731.81412737, 41015.55708641, 52033.72818305, 35527.23097608,
       25303.12301261, 36494.03996199, 36688.32304647, 35826.51769434,
       47334.38882548, 45971.16054321, 44806.68292955, 27789.57095574,
       50531.91304271, 46829.47085744, 33272.97210625, 40080.92308753,
       15821.17728949, 51706.04815075, 41321.11684481, 39172.79222897,
       47629.5707835 , 67355.55689102, 25492.33272751, 41679.44337221,
      

In [34]:
#model performance

from sklearn.metrics import mean_squared_error, r2_score

In [35]:
mean_squared_error(y_test, y_test_pred)

160031907.61713442

In [36]:
r2_score(y_test, y_test_pred)

0.5028901447877382

Classification Tree

In [59]:
df = pd.read_csv('Movie_classification.csv', header = 0)

In [38]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [60]:
df['Time_taken'].fillna(value = df['Time_taken'].mean(), inplace = True)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [63]:
#Dummy variable Creation
df = pd.get_dummies(df, columns = ['3D_available', 'Genre'],drop_first=True)

In [44]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Time_taken Twitter_hastags  \
0            7.995           7.94  ...        None         223.840   
1            7.470           7.44  ...        None         243.456   
2            7.515           7.44  ...        None        2022.400   
3            7.020           8.26  ...        None         225.344   
4            7.070           8.26  ...        None         225.792   

   Avg_age_actors  Num_multiplex  Collection  Start_Tech_Oscar  \
0              23            494       48000                 1   
1              42            462       43200                 0   
2              38            458       69400                 1   
3              45            472       66800                 1   
4              55            395       72400                 1   

   3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0              True         False        False            True  
1             False         False         True           False  
2             False          True        False           False  
3              True         False         True           False  
4             False         False         True           False  

[5 rows x 21 columns]

In [64]:
X = df.loc[:, df.columns != 'Start_Tech_Oscar']
y = df['Start_Tech_Oscar']

In [47]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Start_Tech_Oscar, dtype: int64

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state = 0)

In [51]:
X_train.shape

(404, 20)

In [52]:
X_test.shape

(102, 20)

In [67]:
from sklearn.preprocessing import StandardScaler

In [68]:
sc = StandardScaler().fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [55]:
X_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

In [57]:
from sklearn import svm

In [69]:
clf_svm_1 = svm.SVC(kernel = 'linear', C = 0.01)
clf_svm_1.fit(X_train_std, y_train)

SVC(C=0.01, kernel='linear')

In [70]:
y_train_pred = clf_svm_1.predict(X_train_std)
y_test_pred = clf_svm_1.predict(X_test_std)

In [71]:
y_test_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0])

In [74]:
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix

In [75]:
confusion_matrix(y_test, y_test_pred)

array([[11, 33],
       [ 5, 53]])

In [76]:
accuracy_score(y_test, y_test_pred)

0.6274509803921569

In [78]:
clf_svm_1.n_support_

array([186, 189], dtype=int32)

In [79]:
#Grid Search

from sklearn.model_selection import GridSearchCV

In [80]:
params = {'C': (0.001,0.005,0.01,0.05, 0.1, 0.5,1,5,10,50,100,500,1000 )}

In [82]:
clf_svm_1 = svm.SVC(kernel = 'linear')

In [84]:
svm_grid_lin = GridSearchCV(clf_svm_1, params, cv = 10, n_jobs = -1, verbose = 1, scoring = 'accuracy')

In [85]:
svm_grid_lin.fit(X_train_std, y_train)

Fitting 10 folds for each of 13 candidates, totalling 130 fits


GridSearchCV(cv=10, estimator=SVC(kernel='linear'), n_jobs=-1,
             param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50,
                               100, 500, 1000)},
             scoring='accuracy', verbose=1)

In [86]:
svm_grid_lin.best_params_

{'C': 0.1}

In [87]:
linsvm_clf = svm_grid_lin.best_estimator_

In [88]:
accuracy_score(y_test, linsvm_clf.predict(X_test_std))

0.5980392156862745

In [89]:
#Polynomial Kernal

In [90]:
clf_svm_p3 = svm.SVC(kernel = 'poly', degree = 2, C = 0.1)
clf_svm_p3.fit(X_train_std, y_train)

SVC(C=0.1, degree=2, kernel='poly')

In [91]:
y_train_pred = clf_svm_p3.predict(X_train_std)
y_test_pred = clf_svm_p3.predict(X_test_std)

In [92]:
accuracy_score(y_test, y_test_pred)

0.5588235294117647

In [93]:
clf_svm_p3.n_support_

array([185, 194], dtype=int32)

In [94]:
#Radial Kernal
clf_svm_r = svm.SVC(kernel = 'rbf', gamma = 0.5, C=10)
clf_svm_r.fit(X_train_std, y_train)

SVC(C=10, gamma=0.5)

In [95]:
y_train_pred = clf_svm_r.predict(X_train_std)
y_test_pred = clf_svm_r.predict(X_test_std)

In [96]:
accuracy_score(y_test, y_test_pred)

0.6176470588235294

In [97]:
clf_svm_r.n_support_

array([186, 218], dtype=int32)

In [98]:
#Radial Grid
params = {'C' : (0.01,0.05, 0.1,0.5,5, 1, 10, 50, 100), 'gamma' : (0.001, 0.01, 0.1, 1, 10, 100)}

In [99]:
clf_svm_r = svm.SVC(kernel = 'rbf')

In [100]:
svm_grid_rad = GridSearchCV(clf_svm_r, params, cv = 3, n_jobs = -1, verbose = 1, scoring = 'accuracy')

In [103]:
svm_grid_rad.fit(X_train_std, y_train)

Fitting 3 folds for each of 54 candidates, totalling 162 fits


GridSearchCV(cv=3, estimator=SVC(), n_jobs=-1,
             param_grid={'C': (0.01, 0.05, 0.1, 0.5, 5, 1, 10, 50, 100),
                         'gamma': (0.001, 0.01, 0.1, 1, 10, 100)},
             scoring='accuracy', verbose=1)

In [104]:
svm_grid_rad.best_params_

{'C': 50, 'gamma': 0.001}

In [105]:
radsvm_clf = svm_grid_rad.best_estimator_

In [106]:
accuracy_score(y_test, radsvm_clf.predict(X_test_std))

0.6176470588235294